version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-test-and-release:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install            #  Install dependencies
            - run: yarn build              #  Production build
            - run: yarn lint               #  Test Code Style
            - run: yarn test               #  Run unit tests
            - run: yarn semantic-release   #  Release to npm
workflows:
  build-test-and-release:
    jobs:
      - build-test-and-release
